config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :recipes

  root "recipes#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/direction.rb
class Direction < ApplicationRecord
  belongs_to :recipe
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :recipe
end

app/models/recipe.rb
require 'uploads'

class Recipe < ApplicationRecord
	belongs_to :user, optional: true

	has_many :ingredients, inverse_of: :recipe
	has_many :directions, inverse_of: :recipe
	accepts_nested_attributes_for :ingredients, reject_if: :all_blank, allow_destroy: true
	accepts_nested_attributes_for :directions, reject_if: proc { |attributes| attributes['step'].blank? }, allow_destroy: true
	
	validates :title, :description, presence: :true

	has_one_attached :image

	validate :image_format


	def image_variant
  	variation =
    ActiveStorage::Variation.new(Uploads.resize_to_fill(width: 400, height: 400, blob: image.blob))
  	ActiveStorage::Variant.new(image.blob, variation)
	end


	private

	def image_format
  	return unless image.attached?
  	return if image.blob.content_type.start_with? 'image/'
  	image.purge_later
  	errors.add(:image, ': File type is not allowed')
	end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :recipes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
	before_action :find_recipe, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!, except: [:index, :show]
	def index
		@recipe = Recipe.all.order("created_at DESC")
	end

	def show
	end

	def new
		@recipe = current_user.recipes.build
	end

	def create
		@recipe = current_user.recipes.build(recipe_params)

		if @recipe.save
			redirect_to @recipe, notice: "Successfully created new recipe"
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @recipe.update(recipe_params)
			redirect_to @recipe, notice: "Recipe was successfully updated"
		else
			render 'edit'
		end
	end

	def destroy
		@recipe.destroy
		redirect_to root_path, notice: "Successfully deleted recipe"
	end

	private

	def recipe_params
		params.require(:recipe).permit(:title, :description, :image, ingredients_attributes: [:id, :name, :_destroy], directions_attributes: [:id, :step, :_destroy])
	end

	def find_recipe
		@recipe = Recipe.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Recipe App</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  	<nav class="navbar navbar-default">
  		<div class="container">
    		<p class="navbar-brand"> <%= link_to "Recipe Box", root_path %></p>
    		
        <% if user_signed_in? %>
          <ul class="nav navbar-nav navbar-right">
      	 		<li><%= link_to "New Recipe", new_recipe_path %></li>
      	 		<li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
    		  </ul>
        <% else %>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Sign Up", new_user_registration_path %></li>
            <li><%= link_to "Sign In", new_user_session_path %></li>
          </ul>
        <% end %>
  		</div>
    </nav>

    <div class="container">
    	<% flash.each do |name, msg| %>
    		<%= content_tag :div, msg, class: "alert" %>
    	<% end %>
    	<%= yield %>
    </div>

  </body>
</html>

app/views/recipes/_direction_fields.html.erb
<div class='nested-fields'>
	<div class="form-inline clearfix">
    	<div class="field">
    	  <%= f.label :step %>
    	  <br>
    	  <%= f.text_field :step, class: 'form-control' %>
    	</div>
    	<%= link_to_remove_association "Remove", f, class: 'btn-link' %>
  	</div>
</div>

app/views/recipes/_form.html.erb
<%= form_for @recipe do |f| %>
  <% if @recipe.errors.any? %>
    <div id="error_explanation">
      <p>
        <%= pluralize(@recipe.errors.count, "error") %> prevented this recipe from saving:
      </p>

      <ul>
      <% @recipe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="panel-body">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class="panel-body">
    <%= f.label :description %>
    <%= f.text_area :description, class: 'form-control' %>
  </div>
  <div class="panel-body">
    <%= f.label :image %>
    <%= f.file_field :image, class: 'form-control' %>
  </div>

  <div class="row">
    <div class="col-md-6">
      <h3>Ingredients</h3>
      <div id="ingredients">
        <%= f.fields_for :ingredients do |ingredient| %>
          <%= render 'ingredient_fields', f: ingredient %>
        <% end %>
        <div class="links">
          <%= link_to_add_association "Add Ingredient", f, :ingredients, class: 'btn btn-default add-button' %>
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <h3>Directions</h3>
      <div id="directions">
        <%= f.fields_for :directions do |direction| %>
          <%= render 'direction_fields', f: direction %>
        <% end %>
        <div class="links">
          <%= link_to_add_association "Add Step", f, :directions, class: 'btn btn-default add-button' %>
        </div>
      </div>
    </div>
  </div>
  
  <div>
    <%= f.submit class: 'btn btn-primary' %>
  </div>

<% end %>

app/views/recipes/_ingredient_fields.html.erb
<div class='nested-fields'>
	<div class="form-inline clearfix">
    	<div class="field">
    	  <%= f.label :name %>
    	  <br>
    	  <%= f.text_field :name, class: 'form-control' %>
    	</div>
		<%= link_to_remove_association "Remove", f, class: 'btn-link' %>
	</div>
</div>

app/views/recipes/edit.html.erb
<h1> Edit Recipe </h1>

<%= render 'form' %>

app/views/recipes/index.html.erb
<% @recipe.each_slice(3) do |recipes| %>
	<div class="row">
		<% recipes.each do |recipe| %>
			<div class="col-md-4">
				<div class="recipe">
					<div class="image_wrapper">
						<%= link_to recipe do %>
							<% if recipe.image.attached? %>
								<%= image_tag recipe.image_variant %>
							<% end %>
						<% end %>
					</div>
					<h2>
						<%= link_to recipe.title, recipe %>
					</h2>
				</div>
			</div>
		<% end %>
	</div>
<% end %>

app/views/recipes/new.html.erb
<h1> New recipe </h1>

<%= render 'form' %>

<br>

<div class="btn btn-default">
	<%= link_to "Back", root_path %>
</div>

app/views/recipes/show.html.erb
<div class="main_content">
	<div id="recipe_top" class="row">
		<div class="col-md-4">
				<% if @recipe.image.attached? %>
					<%= image_tag @recipe.image_variant, class: 'recipe_image' %>
				<% end %>
		</div>
		<div class="col-md-8">
			<div id="recipe_info">
				<h1><%= @recipe.title %></h1>
				<p class="description"><%= @recipe.description %></p>
				<!-- <p><br>Submitted by <%= @recipe.user.email %></p> -->
			</div>
		</div>
	</div>

	<div class="row">
		<div class="col-md-6">
			<div id="ingredients">
				<h2>Ingredients</h2>
				<ul>
					<% @recipe.ingredients.each do |ingredient| %>
						<li><%= ingredient.name %></li>
					<% end %>
				</ul>
			</div>
		</div>

		<div class="col-md-6">
			<div id="directions">
				<h2>Directions</h2>
				<ul>
					<% @recipe.directions.each do |direction| %>
						<li><%= direction.step %></li>
					<% end %>
				</ul>
			</div>
		</div>
	</div>

	<div class="row">
		<div class="col-md-12">
			<div class="btn btn-default">
				<%= link_to "Back", root_path %>
			</div>
		<% if user_signed_in? %>
			<div class="btn btn-default">
				<%= link_to "Edit", edit_recipe_path %>
			</div>
			<div class="btn btn-default">
				<%= link_to "Delete", recipe_path, method: :delete, data: {confirm: "Are you sure?"} %>
			</div>
		<% end %>
		</div>
	</div>
</div>